name: Tests

on: push

jobs:
  lint:
    name: Test code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - name: Install dependencies
          run: composer install
      - name: Run tests
          run: php artisan test
      - name: Upload artifact after tests
        if: always()
        uses: actions/upload-artifact@v2
        with:
            name: Logs
            path: ./storage/logs
      - name: Download artifact
        if: always()
        uses: actions/download-artifact@v2
        with:
          name: Logs
